include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DIR = $(LIB_PATH)

LIBRARY_NAME = libSCDWrapper


libSCDWrapper_HEADER_FILES= SCDWrapper.h
libSCDWrapper_HEADER_FILES_INSTALL_DIR	= ./include
libSCDWrapper_OBJC_FILES=

libSCDWrapper_C_FILES= SCDWrapper.c


include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/library.make
-include GNUmakefile.postamble




DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)

