/*
 * MATLAB Compiler: 4.1 (R14SP1)
 * Date: Tue Jul 19 14:09:50 2005
 * Arguments: "-B" "macro_default" "-W" "lib:scdlib" "-T" "link:lib"
 * "PlotSCD.m" "dfsm_pace.m" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_scdlib_public_data[] = {'3', '0', '8', '1', '9',
                                                  'D', '3', '0', '0', 'D',
                                                  '0', '6', '0', '9', '2',
                                                  'A', '8', '6', '4', '8',
                                                  '8', '6', 'F', '7', '0',
                                                  'D', '0', '1', '0', '1',
                                                  '0', '1', '0', '5', '0',
                                                  '0', '0', '3', '8', '1',
                                                  '8', 'B', '0', '0', '3',
                                                  '0', '8', '1', '8', '7',
                                                  '0', '2', '8', '1', '8',
                                                  '1', '0', '0', 'C', '4',
                                                  '9', 'C', 'A', 'C', '3',
                                                  '4', 'E', 'D', '1', '3',
                                                  'A', '5', '2', '0', '6',
                                                  '5', '8', 'F', '6', 'F',
                                                  '8', 'E', '0', '1', '3',
                                                  '8', 'C', '4', '3', '1',
                                                  '5', 'B', '4', '3', '1',
                                                  '5', '2', '7', '7', 'E',
                                                  'D', '3', 'F', '7', 'D',
                                                  'A', 'E', '5', '3', '0',
                                                  '9', '9', 'D', 'B', '0',
                                                  '8', 'E', 'E', '5', '8',
                                                  '9', 'F', '8', '0', '4',
                                                  'D', '4', 'B', '9', '8',
                                                  '1', '3', '2', '6', 'A',
                                                  '5', '2', 'C', 'C', 'E',
                                                  '4', '3', '8', '2', 'E',
                                                  '9', 'F', '2', 'B', '4',
                                                  'D', '0', '8', '5', 'E',
                                                  'B', '9', '5', '0', 'C',
                                                  '7', 'A', 'B', '1', '2',
                                                  'E', 'D', 'E', '2', 'D',
                                                  '4', '1', '2', '9', '7',
                                                  '8', '2', '0', 'E', '6',
                                                  '3', '7', '7', 'A', '5',
                                                  'F', 'E', 'B', '5', '6',
                                                  '8', '9', 'D', '4', 'E',
                                                  '6', '0', '3', '2', 'F',
                                                  '6', '0', 'C', '4', '3',
                                                  '0', '7', '4', 'A', '0',
                                                  '4', 'C', '2', '6', 'A',
                                                  'B', '7', '2', 'F', '5',
                                                  '4', 'B', '5', '1', 'B',
                                                  'B', '4', '6', '0', '5',
                                                  '7', '8', '7', '8', '5',
                                                  'B', '1', '9', '9', '0',
                                                  '1', '4', '3', '1', '4',
                                                  'A', '6', '5', 'F', '0',
                                                  '9', '0', 'B', '6', '1',
                                                  'F', 'C', '2', '0', '1',
                                                  '6', '9', '4', '5', '3',
                                                  'B', '5', '8', 'F', 'C',
                                                  '8', 'B', 'A', '4', '3',
                                                  'E', '6', '7', '7', '6',
                                                  'E', 'B', '7', 'E', 'C',
                                                  'D', '3', '1', '7', '8',
                                                  'B', '5', '6', 'A', 'B',
                                                  '0', 'F', 'A', '0', '6',
                                                  'D', 'D', '6', '4', '9',
                                                  '6', '7', 'C', 'B', '1',
                                                  '4', '9', 'E', '5', '0',
                                                  '2', '0', '1', '1', '1'
                                                  , '\0'};

const char *__MCC_scdlib_name_data = "scdlib";

const char *__MCC_scdlib_root_data = "";

const unsigned char __MCC_scdlib_session_data[] = {'7', '9', '8', '6', 'A',
                                                   '5', '2', 'D', '7', '3',
                                                   'B', '8', 'F', 'B', 'C',
                                                   '3', 'D', '8', 'C', 'C',
                                                   'A', '7', '5', 'F', 'F',
                                                   '9', '5', '7', 'A', 'C',
                                                   '4', '7', 'B', '0', '3',
                                                   '4', '3', 'C', 'D', '0',
                                                   '0', 'F', 'A', '7', 'E',
                                                   'B', 'B', 'A', 'C', '8',
                                                   '7', '8', '4', '3', '4',
                                                   'E', '8', '2', '7', '1',
                                                   'A', '4', 'A', '2', '1',
                                                   '8', '1', 'D', 'A', 'B',
                                                   'F', '8', '7', '4', '6',
                                                   '4', '1', 'A', 'D', '0',
                                                   '2', 'C', 'F', 'E', '2',
                                                   '7', '3', 'F', '5', '1',
                                                   'C', '2', '7', 'E', 'C',
                                                   '0', 'F', '8', 'C', '8',
                                                   'C', '0', '4', '8', 'B',
                                                   'E', '0', 'C', '4', 'A',
                                                   'C', '2', 'F', '9', 'C',
                                                   'A', '0', 'E', '1', '1',
                                                   'F', '2', '3', '8', '6',
                                                   'D', '3', '9', 'F', '2',
                                                   'A', 'C', '1', 'E', '6',
                                                   '6', '5', '1', '0', 'E',
                                                   '1', '5', '7', 'E', '4',
                                                   '7', '5', '2', '2', '5',
                                                   '1', '0', 'C', '2', 'D',
                                                   '5', 'B', 'D', '3', '2',
                                                   '6', 'F', 'E', '9', '3',
                                                   'B', 'D', 'B', 'E', 'F',
                                                   '7', '6', 'A', '3', '4',
                                                   '6', '7', 'C', 'A', '5',
                                                   '1', 'D', 'E', '2', '3',
                                                   '6', '9', '3', '3', '2',
                                                   '4', '1', '2', 'D', 'F',
                                                   'A', '4', '3', '1', 'B',
                                                   '9', '2', 'A', 'E', '0',
                                                   'F', '7', '9', '7', '4',
                                                   '0', 'D', 'A', '7', '7',
                                                   '5', '7', '4', '4', '5',
                                                   '9', 'A', '0', '7', 'B',
                                                   '2', '9', 'E', 'E', '5',
                                                   '4', '6', '9', '5', '1',
                                                   'E', '3', '8', 'E', '9',
                                                   'A', '2', '2', '5', '0',
                                                   '0', 'F', '8', '0', 'D',
                                                   '7', 'A', '7', 'D', '2',
                                                   'E', '\0'};

const char *__MCC_scdlib_matlabpath_data[] = {"scdlib/",
                                              "toolbox/compiler/deploy/",
                                              "Users/frank/Matlab/CycloStationary/cyclostationary_toolbox/",
                                              "$TOOLBOXMATLABDIR/general/",
                                              "$TOOLBOXMATLABDIR/ops/",
                                              "$TOOLBOXMATLABDIR/lang/",
                                              "$TOOLBOXMATLABDIR/elmat/",
                                              "$TOOLBOXMATLABDIR/elfun/",
                                              "$TOOLBOXMATLABDIR/specfun/",
                                              "$TOOLBOXMATLABDIR/matfun/",
                                              "$TOOLBOXMATLABDIR/datafun/",
                                              "$TOOLBOXMATLABDIR/polyfun/",
                                              "$TOOLBOXMATLABDIR/funfun/",
                                              "$TOOLBOXMATLABDIR/sparfun/",
                                              "$TOOLBOXMATLABDIR/scribe/",
                                              "$TOOLBOXMATLABDIR/graph2d/",
                                              "$TOOLBOXMATLABDIR/graph3d/",
                                              "$TOOLBOXMATLABDIR/specgraph/",
                                              "$TOOLBOXMATLABDIR/graphics/",
                                              "$TOOLBOXMATLABDIR/uitools/",
                                              "$TOOLBOXMATLABDIR/strfun/",
                                              "$TOOLBOXMATLABDIR/imagesci/",
                                              "$TOOLBOXMATLABDIR/iofun/",
                                              "$TOOLBOXMATLABDIR/audiovideo/",
                                              "$TOOLBOXMATLABDIR/timefun/",
                                              "$TOOLBOXMATLABDIR/datatypes/",
                                              "$TOOLBOXMATLABDIR/verctrl/",
                                              "$TOOLBOXMATLABDIR/codetools/",
                                              "$TOOLBOXMATLABDIR/helptools/",
                                              "$TOOLBOXMATLABDIR/winfun/",
                                              "$TOOLBOXMATLABDIR/demos/",
                                              "toolbox/local/",
                                              "toolbox/stateflow/stateflow/",
                                              "toolbox/compiler/",
                                              "toolbox/control/control/",
                                              "toolbox/nnet/nnet/",
                                              "toolbox/nnet/nnutils/",
                                              "toolbox/robust/robust/",
                                              "toolbox/symbolic/"};
const int __MCC_scdlib_matlabpath_data_count = 39;

const char *__MCC_scdlib_classpath_data[] = {"java/jar/toolbox/control.jar"};
const int __MCC_scdlib_classpath_data_count = 1;

const char *__MCC_scdlib_mcr_application_options[] = { "" };
const int __MCC_scdlib_mcr_application_option_count = 0;
const char *__MCC_scdlib_mcr_runtime_options[] = { "" };
const int __MCC_scdlib_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


